#!/bin/bash

echo "Running Hive Enviroment Path"
export HADOOP_HOME=/usr/local/Cellar/hadoop/3.2.1_1/libexec
export PATH=$PATH:$HADOOP_HOME/bin
export PATH=$PATH:$HADOOP_HOME/sbin
export HIVE_HOME=/usr/local/Cellar/hive/3.1.2_1/libexec
export PATH=$PATH:$HIVE_HOME/bin
export PATH=$PATH:/usr/local/mysql-5.6.22-osx10.8-x86_64/bin
export JAVA_HOME=/usr/local/Cellar/openjdk/13.0.2+8_2/libexec
export PATH=$PATH:$JAVA_HOME/bin
echo "Completed Running Hive Enviroment Path"
